name: th-printf
version: 0.7
synopsis: Quasiquoters for printf
description: Quasiquoters for string and text printf
author: Jude Taylor
maintainer: me@jude.xyz
tested-with: GHC == 8.2.2, GHC == 8.4.4, GHC == 8.6.5, GHC == 8.8.1
extra-source-files:
  - CHANGELOG.md
  - include/compat-defs.h
category: Text
github: pikajude/th-printf

ghc-options: -Wall

flags:
  werror:
    description: Build with -Werror
    default:     False
    manual:      True

when:
  - condition: impl(ghcjs)
    dependencies: [primitive == 0.6.3.0]
  - condition: flag(werror)
    ghc-options: -Werror

dependencies:
  - base == 4.*

library:
  source-dirs: [src, parser]
  exposed-modules:
    - Language.Haskell.Printf
    - Language.Haskell.Printf.Lib
  dependencies:
    - charset
    - containers
    - microlens-platform
    - mtl
    - parsec
    - semigroups
    - template-haskell
    - th-lift
    - transformers
    - text
    - dlist
    - integer-logarithms
  cpp-options: -include include/compat-defs.h
  default-extensions: CPP

tests:
  format:
    source-dirs: tests/printf
    main: format.hs
    dependencies:
      - HUnit
      - QuickCheck
      - hspec
      - template-haskell
      - th-printf
      - text
    ghc-options: -fno-warn-type-defaults
    when:
      - condition: impl(ghcjs)
        dependencies: [hspec-core == 2.4.8]